package kadrovskaslike;
// Generated Sep 30, 2014 11:09:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * BracnoStanje generated by hbm2java
 */
public class BracnoStanje  implements java.io.Serializable {


     private long brsPid;
     private String naziv;
     private Set djelatniks = new HashSet(0);

    public BracnoStanje() {
    }

	
    public BracnoStanje(long brsPid, String naziv) {
        this.brsPid = brsPid;
        this.naziv = naziv;
    }
    public BracnoStanje(long brsPid, String naziv, Set djelatniks) {
       this.brsPid = brsPid;
       this.naziv = naziv;
       this.djelatniks = djelatniks;
    }
   
    public long getBrsPid() {
        return this.brsPid;
    }
    
    public void setBrsPid(long brsPid) {
        this.brsPid = brsPid;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set getDjelatniks() {
        return this.djelatniks;
    }
    
    public void setDjelatniks(Set djelatniks) {
        this.djelatniks = djelatniks;
    }




}


