package kadrovskaslike;
// Generated Sep 30, 2014 11:09:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PoslovnaJedinica generated by hbm2java
 */
public class PoslovnaJedinica  implements java.io.Serializable {


     private long pjePid;
     private String naziv;
     private Set radnaJedinicas = new HashSet(0);

    public PoslovnaJedinica() {
    }

	
    public PoslovnaJedinica(long pjePid, String naziv) {
        this.pjePid = pjePid;
        this.naziv = naziv;
    }
    public PoslovnaJedinica(long pjePid, String naziv, Set radnaJedinicas) {
       this.pjePid = pjePid;
       this.naziv = naziv;
       this.radnaJedinicas = radnaJedinicas;
    }
   
    public long getPjePid() {
        return this.pjePid;
    }
    
    public void setPjePid(long pjePid) {
        this.pjePid = pjePid;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set getRadnaJedinicas() {
        return this.radnaJedinicas;
    }
    
    public void setRadnaJedinicas(Set radnaJedinicas) {
        this.radnaJedinicas = radnaJedinicas;
    }




}


