package kadrovskaslike;
// Generated Sep 30, 2014 11:09:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RadnaJedinica generated by hbm2java
 */
public class RadnaJedinica  implements java.io.Serializable {


     private long rjePid;
     private Djelatnik djelatnik;
     private PoslovnaJedinica poslovnaJedinica;
     private String naziv;
     private Long gppPid;
     private Long mt;
     private Boolean aktivno;
     private Set djelatniks = new HashSet(0);

    public RadnaJedinica() {
    }

	
    public RadnaJedinica(long rjePid, PoslovnaJedinica poslovnaJedinica, String naziv) {
        this.rjePid = rjePid;
        this.poslovnaJedinica = poslovnaJedinica;
        this.naziv = naziv;
    }
    public RadnaJedinica(long rjePid, Djelatnik djelatnik, PoslovnaJedinica poslovnaJedinica, String naziv, Long gppPid, Long mt, Boolean aktivno, Set djelatniks) {
       this.rjePid = rjePid;
       this.djelatnik = djelatnik;
       this.poslovnaJedinica = poslovnaJedinica;
       this.naziv = naziv;
       this.gppPid = gppPid;
       this.mt = mt;
       this.aktivno = aktivno;
       this.djelatniks = djelatniks;
    }
   
    public long getRjePid() {
        return this.rjePid;
    }
    
    public void setRjePid(long rjePid) {
        this.rjePid = rjePid;
    }
    public Djelatnik getDjelatnik() {
        return this.djelatnik;
    }
    
    public void setDjelatnik(Djelatnik djelatnik) {
        this.djelatnik = djelatnik;
    }
    public PoslovnaJedinica getPoslovnaJedinica() {
        return this.poslovnaJedinica;
    }
    
    public void setPoslovnaJedinica(PoslovnaJedinica poslovnaJedinica) {
        this.poslovnaJedinica = poslovnaJedinica;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Long getGppPid() {
        return this.gppPid;
    }
    
    public void setGppPid(Long gppPid) {
        this.gppPid = gppPid;
    }
    public Long getMt() {
        return this.mt;
    }
    
    public void setMt(Long mt) {
        this.mt = mt;
    }
    public Boolean getAktivno() {
        return this.aktivno;
    }
    
    public void setAktivno(Boolean aktivno) {
        this.aktivno = aktivno;
    }
    public Set getDjelatniks() {
        return this.djelatniks;
    }
    
    public void setDjelatniks(Set djelatniks) {
        this.djelatniks = djelatniks;
    }




}


