package kadrovskaslike;
// Generated Sep 30, 2014 11:09:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * StrucnaSprema generated by hbm2java
 */
public class StrucnaSprema  implements java.io.Serializable {


     private long sspPid;
     private String naziv;
     private String stupanj;
     private Set posaos = new HashSet(0);
     private Set djelatniks = new HashSet(0);

    public StrucnaSprema() {
    }

	
    public StrucnaSprema(long sspPid, String naziv) {
        this.sspPid = sspPid;
        this.naziv = naziv;
    }
    public StrucnaSprema(long sspPid, String naziv, String stupanj, Set posaos, Set djelatniks) {
       this.sspPid = sspPid;
       this.naziv = naziv;
       this.stupanj = stupanj;
       this.posaos = posaos;
       this.djelatniks = djelatniks;
    }
   
    public long getSspPid() {
        return this.sspPid;
    }
    
    public void setSspPid(long sspPid) {
        this.sspPid = sspPid;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getStupanj() {
        return this.stupanj;
    }
    
    public void setStupanj(String stupanj) {
        this.stupanj = stupanj;
    }
    public Set getPosaos() {
        return this.posaos;
    }
    
    public void setPosaos(Set posaos) {
        this.posaos = posaos;
    }
    public Set getDjelatniks() {
        return this.djelatniks;
    }
    
    public void setDjelatniks(Set djelatniks) {
        this.djelatniks = djelatniks;
    }




}


