package kadrovskaslike;
// Generated Sep 30, 2014 11:09:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vjera generated by hbm2java
 */
public class Vjera  implements java.io.Serializable {


     private long vjePid;
     private String naziv;
     private Set djelatniks = new HashSet(0);

    public Vjera() {
    }

	
    public Vjera(long vjePid, String naziv) {
        this.vjePid = vjePid;
        this.naziv = naziv;
    }
    public Vjera(long vjePid, String naziv, Set djelatniks) {
       this.vjePid = vjePid;
       this.naziv = naziv;
       this.djelatniks = djelatniks;
    }
   
    public long getVjePid() {
        return this.vjePid;
    }
    
    public void setVjePid(long vjePid) {
        this.vjePid = vjePid;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set getDjelatniks() {
        return this.djelatniks;
    }
    
    public void setDjelatniks(Set djelatniks) {
        this.djelatniks = djelatniks;
    }




}


