package kadrovskaslike;
// Generated Sep 30, 2014 11:09:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VrstaZaposlenja generated by hbm2java
 */
public class VrstaZaposlenja  implements java.io.Serializable {


     private long vrzPid;
     private String naziv;
     private Set djelatniks = new HashSet(0);

    public VrstaZaposlenja() {
    }

	
    public VrstaZaposlenja(long vrzPid, String naziv) {
        this.vrzPid = vrzPid;
        this.naziv = naziv;
    }
    public VrstaZaposlenja(long vrzPid, String naziv, Set djelatniks) {
       this.vrzPid = vrzPid;
       this.naziv = naziv;
       this.djelatniks = djelatniks;
    }
   
    public long getVrzPid() {
        return this.vrzPid;
    }
    
    public void setVrzPid(long vrzPid) {
        this.vrzPid = vrzPid;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set getDjelatniks() {
        return this.djelatniks;
    }
    
    public void setDjelatniks(Set djelatniks) {
        this.djelatniks = djelatniks;
    }




}


