package kadrovskaslike;
// Generated Sep 30, 2014 11:09:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VrstaRada generated by hbm2java
 */
public class VrstaRada  implements java.io.Serializable {


     private long vrrPid;
     private String naziv;
     private boolean porez;
     private Set djelatniks = new HashSet(0);

    public VrstaRada() {
    }

	
    public VrstaRada(long vrrPid, String naziv, boolean porez) {
        this.vrrPid = vrrPid;
        this.naziv = naziv;
        this.porez = porez;
    }
    public VrstaRada(long vrrPid, String naziv, boolean porez, Set djelatniks) {
       this.vrrPid = vrrPid;
       this.naziv = naziv;
       this.porez = porez;
       this.djelatniks = djelatniks;
    }
   
    public long getVrrPid() {
        return this.vrrPid;
    }
    
    public void setVrrPid(long vrrPid) {
        this.vrrPid = vrrPid;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public boolean isPorez() {
        return this.porez;
    }
    
    public void setPorez(boolean porez) {
        this.porez = porez;
    }
    public Set getDjelatniks() {
        return this.djelatniks;
    }
    
    public void setDjelatniks(Set djelatniks) {
        this.djelatniks = djelatniks;
    }




}


